config/routes.rb
Rails.application.routes.draw do
  root 'static#home', as: 'home'
  get '/recipes/most_collected', to: 'recipes#most_collected'

  resources :recipes, only: [:index, :destroy]
  resources :recipes, only: [:show] do
    resources :reviews, only: [:create]
  end

  resources :reviews, only: [:show]

  resources :user, only: [:show] do
    resources :collections, only: [:index, :show, :new, :create, :edit, :update]
    resources :recipes, only: [:index, :show, :new, :create, :edit, :update]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :cook, class_name: 'User'
  has_many :recipe_collections
  has_many :recipes, through: :recipe_collections
  validates :name, presence: true

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :quantities
  has_many :recipes, through: :quantities
  validates :name, uniqueness: true

end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  def ingredient_attributes=(ingredient)
    self.ingredient = Ingredient.find_or_create_by(name: ingredient.fetch("name"))
    self.ingredient.update(ingredient)
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :quantities
  has_many :quantities, inverse_of: :recipe
  has_many :ingredients, through: :quantities
  has_many :recipe_collections
  has_many :collections, through: :recipe_collections
  has_many :cooks, through: :collections, class_name: 'User'
  validates :name, :user_id, presence: true
  validates :name, uniqueness: true
  accepts_nested_attributes_for :quantities, reject_if: :all_blank, allow_destroy: true

end

app/models/recipe_collection.rb
class RecipeCollection < ApplicationRecord
  belongs_to :recipe
  belongs_to :collection
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :user_id, :recipe_id, :title, :content, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:github]

  has_many :recipes
  has_many :reviews
  has_many :collections, foreign_key: :cook_id
  has_many :foods, through: :collections, class_name: 'Recipe'

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    recipes_path
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
    if current_user
      user = User.find(params[:user_id])
      @collections = user.collections
      @collection = Collection.new
    else
      redirect_to home_path
    end
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def create
    if !params[:collection][:id]
      collection = Collection.new(collection_params)
      recipe = Recipe.find(params[:collection][:recipe_id])
      collection.recipes << recipe
      if collection.save
        recipe.update(collected_count: recipe.collections.count)
        flash[:notice] = "Your #{collection.name} collection created successfully!"
        redirect_to user_collection_path(params[:collection][:cook_id], collection)
      else
        flash[:notice] = "Your collection was not created successfully."
        render 'index'
      end
    else
      collection = Collection.find(params[:collection][:id])
      recipe = Recipe.find(params[:collection][:recipe_id])
      if !collection.recipes.include?(recipe)
        collection.recipes << recipe
        if collection.save
          recipe.update(collected_count: recipe.collections.count)
          flash[:notice] = "The recipe was successfully added to your collection."
          redirect_to recipes_path
        else
          flash[:notice] = "The recipe was not added to your collection due to an error."
          redirect_to recipes_path
        end
      else
        flash[:error] = "The recipe #{recipe.name} was already in your collection and not added again."
        redirect_back fallback_location: recipes_path
      end
    end
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :cook_id, :recipe_id => [])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def most_collected
    @recipes = policy_scope(Recipe)
  end

  def index
    if (params[:user_id])
      user = User.find(params[:user_id])
      @recipes = user.recipes
      respond_to do |format|
        format.json { render json: @recipes }
        format.html { render :index }
      end
    else
      @recipes = Recipe.all
    end
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @review = Review.new
    respond_to do |format|
      format.json { render json: @recipe, include: '**' }
      format.html { render :show }
    end
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to user_recipe_path(current_user, @recipe)
    else
      render :new
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    if current_user.id == recipe.user_id
      recipe.destroy
      redirect_to recipes_path
    else
      redirect_back
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :user_id, :description, :instructions, quantities_attributes: [:id, :amount, :done, :_destroy, ingredient_attributes: [:id, :name, :_destroy]])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      respond_to do |format|
        format.json { render json: @review }
        format.html { redirect_to recipe_path(@review.recipe) }
      end
    else
      flash[:alert] = "Your review was not saved due to an error."
      redirect_to recipe_path(@review.recipe)
    end
  end
  
  def show
    @review = Review.find(params[:id])
    respond_to do |format|
      format.json { render json: @review, include: '**' }
      format.html { render :show }
    end
  end

  private

  def review_params
    params.require(:review).permit(:recipe_id, :user_id, :title, :content )
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = current_user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/collections/index.html.erb
<h1 class="text-center">Your Collections</h1>

<% @collections.each do |c| %>
  <h4><%= link_to "#{c.name}", user_collection_path(current_user, c) %></h4>
<% end %>

app/views/collections/show.html.erb
<h1><%= @collection.name %></h1>
<% @collection.recipes.each do |r| %>
  <ul>
    <li><%= link_to "#{r.name}", recipe_path(r), class: "recipe-link" %></li>
  </ul>
<% end %>

<div class="recipe-details">
 
</div>

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= render 'layouts/navigation/left_side.html.erb' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation/right_side.html.erb' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe Saver Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/layouts/navigation/_left_side.html.erb
<% if current_user %>
  <%= link_to "Recipe Saver", recipes_path, class: "navbar-brand" %>
<% else %>
  <%= link_to "Recipe Saver", home_path, class: "navbar-brand" %>
<% end %>

app/views/layouts/navigation/_right_side.html.erb
<% if current_user %>
  <!-- need to make path for users to only see their own recipes -->
  <li><%= link_to "Most Collected Recipes", recipes_most_collected_path %></li>
  <li><%= link_to "Your Page", user_path(current_user) %></li>
  <li><%= link_to "Create a Recipe", new_user_recipe_path(current_user) %></li>
  <li><%= link_to "Your Collections", user_collections_path(current_user) %></li>
  <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
<% else %>
  <li><%= link_to "Sign In", new_user_session_path %></li>
  <li><%= link_to "Sign in with Github", user_github_omniauth_authorize_path %></li>
  <li><%= link_to "Sign Up", new_user_registration_path %></li>
<% end %>

app/views/recipes/_collections_form.html.erb
<%= form_for :collection, url: user_collections_path(current_user.id), method: :post do |f| %>
  <%= f.hidden_field :cook_id, { value: current_user.id } %>
  <%= f.hidden_field :recipe_id, { value: r.id } %>

  <div class="form-group">
    <%= f.label :id, "Collection Name: " %>
    <%= f.collection_select(:id, current_user.collections, :id, :name, prompt: "Please Select", class: "form-control") %>
  </div>
  <%= f.submit "Add To Collection" %>
<% end %>
<br><br>

<%= form_for :collection, url: user_collections_path(current_user.id), method: :post do |f| %>
  <%= f.hidden_field :cook_id, { value: current_user.id } %>
  <%= f.hidden_field :recipe_id, { value: r.id } %>

  <div class="form-group">
    <%= f.label :name, "New Collection Name: " %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Create New Collection" %>
<% end %>

app/views/recipes/_form.html.erb
<%= form_for @recipe, url: user_recipes_path(current_user), method: :post do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li> <br>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :user_id, { value: current_user.id }  %>
    <%= f.label :name, "Name: " %>
    <%= f.text_field :name, class: "form-control" %>
  </div> <br> <br>

  <div class="form-group">
  <%= f.label :description, "Description: " %>
  <%= f.text_area :description, class: "form-control" %>
  </div><br> <br>

  <div class="form-group">
    <%= f.label :instructions, "Instructions: " %>
    <%= f.text_area :instructions, class: "form-control" %> <br><br>
  </div>

  <div class="form-nesting">
    <%= f.fields_for :quantities do |quantity| %>
      <%= render 'quantity_fields', f: quantity %>
    <% end %>
    <%= link_to_add_association 'Add Ingredient', f, :quantities, wrap_object: Proc.new {|quantity| quantity.build_ingredient; quantity } %>
  </div>
  

  <br><br>

  <%= f.submit %>
<% end %>

app/views/recipes/_index.html.erb
<div class="row">
  <% @recipes.each do |r| %>
    <div class="col-sm-4 col-lg-3">
      <a href="recipes/<%= r.id %>">
        <h4 class="text-center"><%= r.name %></h4>
        <p class="text-center"><%= pluralize(r.ingredients.count, "Ingredient") %></p>
      </a>

      <%= render partial: 'collections_form', locals: {r: r} %>

    </div>
  <% end %>
</div>

app/views/recipes/_quantity_fields.html.erb
<div class="nested-fields form-group">
<%= f.label :amount, "Ingredient Amount:" %>
<%= f.text_field :amount, class: "form-control" %> <br> <br>

<%= f.fields_for :ingredient do |quantity_ingredient| %>
  <%= quantity_ingredient.label :name, "Ingredient Name:" %>
  <%= quantity_ingredient.text_field :name, class: "form-control" %>
<% end %> <br>

<%= link_to_remove_association "Remove Ingredient", f %>
</div>

app/views/recipes/_review.html.erb
<div class="reviews_container">
  <h2>Reviews</h2>
  <ul class="review_list">
    <% @recipe.reviews.each do |review| %>
      <li class="review">
        <h4 class="review_title"> <%= review.title %> </h4>
        <p class="review_content"> <%= review.content %> </p>
        <p class="review_writer"> Reviewed On: <%= review.updated_at.strftime("%m/%d/%Y") %> </p>
      </li>
    <% end %>
  </ul>
</div>

app/views/recipes/_review_form.html.erb
<br> <br>
<h4>Review this Recipe!</h4>
<%= form_for([@recipe, @review]) do |f| %>
  <%= f.hidden_field :recipe_id, value: @recipe.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.label :content %>
  <%= f.text_area :content  %> <br>
  <%= f.submit %>
<% end %>

app/views/recipes/_script.js.erb
<script type="text/javascript" charset="utf-8">
 $(function () {
   $(".js-next").on("click", function(e) {
    e.preventDefault();
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    getData(nextId, "next");
   });

   $(".js-prev").on("click", function(e) {
     e.preventDefault();
     var prevId = parseInt($(".js-prev").attr("data-id")) - 1;
     getData(prevId, "previous");
   });

   var getData = function(id, direction) {
    $.get("/recipes/" + id + ".json", function(json) {
    })
      .done(function (json) {
          setData(json);
          setLinks(json["id"], json["user"]["id"]);
      })
      .fail(function() {
        if (direction === "next") {
          id++;
        } else if (direction === "previous") {
          id--;
        }
        getData(id, direction);
      })
   };
   
   var setLinks = function(id, userId) {
      //reset the data-id to the new recipe id
       $(".js-next").attr("data-id", id);
       $(".js-prev").attr("data-id", id);

      // reset the clickable links for next and previous 
      if (id === <%= Recipe.all.first.id %>)
      {
        $(".js-next").show();
        $("#link-span").hide();
        $(".js-prev").hide();
      } else if (id === <%= Recipe.all.last.id %>) 
      {
        $(".js-next").hide();
        $("#link-span").hide();
        $(".js-prev").show();
      } else 
      {
        $(".js-next").show();
        $("#link-span").show();
        $(".js-prev").show();
      }

      if (<%= current_user.id %> === userId) {
        $(".recipe-delete").show();
      } else {
        $(".recipe-delete").hide();
      }
   }

   setLinks(<%= @recipe.id %>, <%= @recipe.user.id %>);

   var setData = function(json) {
       $("#recipe-name").text(json["name"]);
       $("#recipe-description").text(json["description"]);
       $("#recipe-instructions").text(json["instructions"]);
       
       // clear and reset the ingredient list
       $("#ingredient-list").empty();
       var quantityArr = json["quantities"];
       quantityArr.forEach(function(q) {
        $("ul#ingredient-list").append("<li class='ingredient-item'>" + q.amount + " - " + q.ingredient.name + "</li>");
      }, this);
      
      // clear and reset the reviews list
      $("ul.review_list").empty();
      var reviewArr = json["reviews"];
      reviewArr.forEach(function(r) {
        var date = new Date(r.updated_at);
        date_options = {day: '2-digit', month: '2-digit', year: 'numeric'};
        $("ul.review_list").append("<li class='review'><h4 class='review_title'>" + r.title + "</h4><p class='review_content'>" + r.content + "</p><p class='review_writer'> Reviewed On: " + date.toLocaleDateString("en-US", date_options) + "</p></li>")
      }, this);
   };
 });
</script>

app/views/recipes/index.html.erb
<h1 class="text-center">Recipes</h1>

<%= render 'index' %>

app/views/recipes/most_collected.html.erb
<div class="row">
  <% @recipes.each do |r| %>
    <div class="col-sm-4 col-lg-3">
      <a href="recipes/<%= r.id %>">
        <h4 class="text-center"><%= r.name %></h4>
        <p class="text-center"><%= pluralize(r.collections.count, "Collection") %></p>
      </a>

      <%= render partial: 'collections_form', locals: {r: r} %>

    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<h1 id="recipe-name"><%= @recipe.name %></h1>
<p id="recipe-description"><%= @recipe.description %></p>

<h3>Ingredients</h3>
<ul id="ingredient-list">
  <% @recipe.quantities.each do |q| %>
    <li class="ingredient-item"><%= q.amount + " - " + q.ingredient.name %></li>
  <% end %>
</ul>

<h3>Instructions</h3>
<p id="recipe-instructions"><%= @recipe.instructions %></p> <br>

<p id="view-links"><%= link_to "Previous Recipe", "#", class: "js-prev", data: { id: @recipe.id } %> <span id="link-span">&emsp; &emsp; &emsp; &emsp;</span>  <%= link_to "Next Recipe", "#", class: "js-next", data: { id: @recipe.id } %></p> <br>

<%= link_to "Delete Recipe", @recipe, method: :delete, class: "recipe-delete" %>

<%= render 'review_form' %>

<%= render 'review' %>

<script id="review-template" type="text/x-handlebars-template">
  <li class="review">
    <h4 class="review_title"> {{title}} </h4>
    <p class="review_content"> {{content}} </p>
    <p class="review_date"> Reviewed On: {{updated_at}} </p>
  </li>
</script>

<%= render partial: "script", formats: "js" %>

app/views/recipes/user_recipes_index.html.erb
<h1 class="text-center">Your Recipes</h1>

<%= render 'index' %>

app/views/user/index.html.erb
<h1 class="text-center home-title">Welcome To Recipe Saver</h1>
<%= video_tag(
  'restaurant.mp4',
  id: 'background-index',
  autoplay: true,
  loop: true,
  muted: true
)
%>

app/views/user/show.html.erb
<h3 class="text-center"> User: <strong><%= @user.email %></strong> </h3>

<%= link_to "See Your Recipes", user_recipes_path(@user), class: "get_user_recipes" %>
<%= link_to "Hide Your Recipes", "#", class: "hide_user_recipes" %>

<div id="recipes">
  <ol id="recipe_list">
  </ol>
</div>